
# alembic/script.py.mako
"""Add topics, genre, transcript_fetched to VideoJob

Revision ID: 76fe211d9bf1
Revises: 8c8bf2b92eb6
Create Date: 2025-04-18 08:42:37.439613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fe211d9bf1'
down_revision: Union[str, None] = '8c8bf2b92eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_value', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_fetched', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'EDITING', 'RENDERING', 'UPLOADING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('script_genre', sa.String(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('editor_data', sa.JSON(), nullable=True),
    sa.Column('selected_music', sa.String(), nullable=True),
    sa.Column('render_path', sa.String(), nullable=True),
    sa.Column('youtube_title', sa.String(), nullable=True),
    sa.Column('youtube_description', sa.Text(), nullable=True),
    sa.Column('youtube_tags', sa.JSON(), nullable=True),
    sa.Column('youtube_id', sa.String(), nullable=True),
    sa.Column('scheduled_upload_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_jobs_id'), 'video_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_video_jobs_source_type'), 'video_jobs', ['source_type'], unique=False)
    op.create_index(op.f('ix_video_jobs_status'), 'video_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_jobs_status'), table_name='video_jobs')
    op.drop_index(op.f('ix_video_jobs_source_type'), table_name='video_jobs')
    op.drop_index(op.f('ix_video_jobs_id'), table_name='video_jobs')
    op.drop_table('video_jobs')
    # ### end Alembic commands ###